# Generated by Django 3.2.25 on 2026-01-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20260113_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='배송지 주소'),
        ),
        migrations.AddField(
            model_name='order',
            name='memo',
            field=models.TextField(blank=True, verbose_name='배송 요청사항'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='연락처'),
        ),
    ]
